
package com.uims.authenticatedUsermanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidImsServiceMethodArgumentException", targetNamespace = "http://uimsv22.service.ims.schneider.com/")
public class InvalidImsServiceMethodArgumentException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidImsServiceMethodArgumentException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidImsServiceMethodArgumentException_Exception(String message, InvalidImsServiceMethodArgumentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidImsServiceMethodArgumentException_Exception(String message, InvalidImsServiceMethodArgumentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.uims.authenticatedUsermanager.InvalidImsServiceMethodArgumentException
     */
    public InvalidImsServiceMethodArgumentException getFaultInfo() {
        return faultInfo;
    }

}
