
package com.uimsv22.schneider.forcephone;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IMSServiceSecurityCallNotAllowedException", targetNamespace = "http://uimsv22.service.ims.schneider.com/")
public class IMSServiceSecurityCallNotAllowedException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IMSServiceSecurityCallNotAllowedException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IMSServiceSecurityCallNotAllowedException_Exception(String message, IMSServiceSecurityCallNotAllowedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IMSServiceSecurityCallNotAllowedException_Exception(String message, IMSServiceSecurityCallNotAllowedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.uimsv22.schneider.forcephone.IMSServiceSecurityCallNotAllowedException
     */
    public IMSServiceSecurityCallNotAllowedException getFaultInfo() {
        return faultInfo;
    }

}
