
package com.schneider.ims.service.company.impl.uimsv2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticatedCompanyManagementV2", targetNamespace = "http://uimsv2.impl.company.service.ims.schneider.com/", wsdlLocation = "https://ims-int.btsec.dev.schneider-electric.com/IMS-CompanyManager/UIMSV2/2WAuthenticated-CompanyManagement?wsdl")
public class AuthenticatedCompanyManagementV2
    extends Service
{

    private final static URL AUTHENTICATEDCOMPANYMANAGEMENTV2_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATEDCOMPANYMANAGEMENTV2_EXCEPTION;
    private final static QName AUTHENTICATEDCOMPANYMANAGEMENTV2_QNAME = new QName("http://uimsv2.impl.company.service.ims.schneider.com/", "AuthenticatedCompanyManagementV2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ims-int.btsec.dev.schneider-electric.com/IMS-CompanyManager/UIMSV2/2WAuthenticated-CompanyManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATEDCOMPANYMANAGEMENTV2_WSDL_LOCATION = url;
        AUTHENTICATEDCOMPANYMANAGEMENTV2_EXCEPTION = e;
    }

    public AuthenticatedCompanyManagementV2() {
        super(__getWsdlLocation(), AUTHENTICATEDCOMPANYMANAGEMENTV2_QNAME);
    }

    public AuthenticatedCompanyManagementV2(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATEDCOMPANYMANAGEMENTV2_QNAME, features);
    }

    public AuthenticatedCompanyManagementV2(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATEDCOMPANYMANAGEMENTV2_QNAME);
    }

    public AuthenticatedCompanyManagementV2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATEDCOMPANYMANAGEMENTV2_QNAME, features);
    }

    public AuthenticatedCompanyManagementV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticatedCompanyManagementV2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticatedCompanyManagerUIMSV2
     */
    @WebEndpoint(name = "AuthenticatedCompanyManager_UIMSV2_ImplPort")
    public AuthenticatedCompanyManagerUIMSV2 getAuthenticatedCompanyManagerUIMSV2ImplPort() {
        return super.getPort(new QName("http://uimsv2.impl.company.service.ims.schneider.com/", "AuthenticatedCompanyManager_UIMSV2_ImplPort"), AuthenticatedCompanyManagerUIMSV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticatedCompanyManagerUIMSV2
     */
    @WebEndpoint(name = "AuthenticatedCompanyManager_UIMSV2_ImplPort")
    public AuthenticatedCompanyManagerUIMSV2 getAuthenticatedCompanyManagerUIMSV2ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uimsv2.impl.company.service.ims.schneider.com/", "AuthenticatedCompanyManager_UIMSV2_ImplPort"), AuthenticatedCompanyManagerUIMSV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATEDCOMPANYMANAGEMENTV2_EXCEPTION!= null) {
            throw AUTHENTICATEDCOMPANYMANAGEMENTV2_EXCEPTION;
        }
        return AUTHENTICATEDCOMPANYMANAGEMENTV2_WSDL_LOCATION;
    }

}
