
package com.schneider.ims.service.company.impl.uimsv2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidImsServiceMethodArgumentException", targetNamespace = "http://uimsv2.service.ims.schneider.com/")
public class InvalidImsServiceMethodArgumentException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.schneider.ims.service.uimsv2.InvalidImsServiceMethodArgumentException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidImsServiceMethodArgumentException(String message, com.schneider.ims.service.uimsv2.InvalidImsServiceMethodArgumentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidImsServiceMethodArgumentException(String message, com.schneider.ims.service.uimsv2.InvalidImsServiceMethodArgumentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.schneider.ims.service.uimsv2.InvalidImsServiceMethodArgumentException
     */
    public com.schneider.ims.service.uimsv2.InvalidImsServiceMethodArgumentException getFaultInfo() {
        return faultInfo;
    }

}
