
package com.uims.accessmanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IMSBadApplicationException", targetNamespace = "http://uimsv2.service.ims.schneider.com/")
public class IMSBadApplicationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IMSBadApplicationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IMSBadApplicationException_Exception(String message, IMSBadApplicationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IMSBadApplicationException_Exception(String message, IMSBadApplicationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.uims.accessmanager.IMSBadApplicationException
     */
    public IMSBadApplicationException getFaultInfo() {
        return faultInfo;
    }

}
