
package com.uims.accessmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UIMSV2_UserAccessManagement", targetNamespace = "http://uimsv2.impl.service.ims.schneider.com/", wsdlLocation = "https://ims-int.btsec.dev.schneider-electric.com/IMS-UserManager/UIMSV2/2WAuthenticated-UserAccessManager?wsdl")
public class UIMSV2UserAccessManagement
    extends Service
{

    private final static URL UIMSV2USERACCESSMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException UIMSV2USERACCESSMANAGEMENT_EXCEPTION;
    private final static QName UIMSV2USERACCESSMANAGEMENT_QNAME = new QName("http://uimsv2.impl.service.ims.schneider.com/", "UIMSV2_UserAccessManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ims-int.btsec.dev.schneider-electric.com/IMS-UserManager/UIMSV2/2WAuthenticated-UserAccessManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UIMSV2USERACCESSMANAGEMENT_WSDL_LOCATION = url;
        UIMSV2USERACCESSMANAGEMENT_EXCEPTION = e;
    }

    public UIMSV2UserAccessManagement() {
        super(__getWsdlLocation(), UIMSV2USERACCESSMANAGEMENT_QNAME);
    }

    public UIMSV2UserAccessManagement(WebServiceFeature... features) {
        super(__getWsdlLocation(), UIMSV2USERACCESSMANAGEMENT_QNAME, features);
    }

    public UIMSV2UserAccessManagement(URL wsdlLocation) {
        super(wsdlLocation, UIMSV2USERACCESSMANAGEMENT_QNAME);
    }

    public UIMSV2UserAccessManagement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UIMSV2USERACCESSMANAGEMENT_QNAME, features);
    }

    public UIMSV2UserAccessManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UIMSV2UserAccessManagement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserAccessManagerUIMSV2
     */
    @WebEndpoint(name = "UserAccessManager_UIMSV2_ImplPort")
    public UserAccessManagerUIMSV2 getUserAccessManagerUIMSV2ImplPort() {
        return super.getPort(new QName("http://uimsv2.impl.service.ims.schneider.com/", "UserAccessManager_UIMSV2_ImplPort"), UserAccessManagerUIMSV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserAccessManagerUIMSV2
     */
    @WebEndpoint(name = "UserAccessManager_UIMSV2_ImplPort")
    public UserAccessManagerUIMSV2 getUserAccessManagerUIMSV2ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uimsv2.impl.service.ims.schneider.com/", "UserAccessManager_UIMSV2_ImplPort"), UserAccessManagerUIMSV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UIMSV2USERACCESSMANAGEMENT_EXCEPTION!= null) {
            throw UIMSV2USERACCESSMANAGEMENT_EXCEPTION;
        }
        return UIMSV2USERACCESSMANAGEMENT_WSDL_LOCATION;
    }

}
