
package com.uimsv22.schneider.forcephone;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ImsMailerException", targetNamespace = "http://uimsv22.service.ims.schneider.com/")
public class ImsMailerException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ImsMailerException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ImsMailerException_Exception(String message, ImsMailerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ImsMailerException_Exception(String message, ImsMailerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.uimsv22.schneider.forcephone.ImsMailerException
     */
    public ImsMailerException getFaultInfo() {
        return faultInfo;
    }

}
