
package com.se.uims.usermanager;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RequestedInternalUserException", targetNamespace = "http://uimsv22.service.ims.schneider.com/")
public class RequestedInternalUserException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RequestedInternalUserException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RequestedInternalUserException_Exception(String message, RequestedInternalUserException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RequestedInternalUserException_Exception(String message, RequestedInternalUserException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.se.uims.usermanager.RequestedInternalUserException
     */
    public RequestedInternalUserException getFaultInfo() {
        return faultInfo;
    }

}
