package com.idms.mail.template.util;

public class EmailTemplateConfiguration {

	private String IDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN;

	private String IDMS_USER_UPDATE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_UPDATE_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_DEFAULT_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_DEFAULT_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN;
	
	private String IDMS_SEND_INVITATION_EMAILTEMPLATE_EN;
	
	private String IDMS_SEND_INVITATION_EMAILTEMPLATE_CN;
	
	private String IDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN;
	
	private String IDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_ADD_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_ADD_EMAILTEMPLATE_EN;
	
	private String IDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN;
	
	private String IDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN;
	
	private String PRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN;
	
	private String PRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN;

	private String PRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN;
	
	private String PRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN;
	
	private String PRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN;
	
	private String PRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN;

	public String getIDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN() {
		return IDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN() {
		return IDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN() {
		return IDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN() {
		return IDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN() {
		return IDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN() {
		return IDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN() {
		return IDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN() {
		return IDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_UPDATE_EMAILTEMPLATE_CN() {
		return IDMS_USER_UPDATE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_UPDATE_EMAILTEMPLATE_EN() {
		return IDMS_USER_UPDATE_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN() {
		return IDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN() {
		return IDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_DEFAULT_EMAILTEMPLATE_CN() {
		return IDMS_USER_DEFAULT_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_DEFAULT_EMAILTEMPLATE_EN() {
		return IDMS_USER_DEFAULT_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN() {
		return IDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN() {
		return IDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN;
	}

	public String getIDMS_SEND_INVITATION_EMAILTEMPLATE_EN() {
		return IDMS_SEND_INVITATION_EMAILTEMPLATE_EN;
	}

	public String getIDMS_SEND_INVITATION_EMAILTEMPLATE_CN() {
		return IDMS_SEND_INVITATION_EMAILTEMPLATE_CN;
	}

	public String getIDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN() {
		return IDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN;
	}

	public String getIDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN() {
		return IDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_ADD_EMAILTEMPLATE_CN() {
		return IDMS_USER_ADD_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_ADD_EMAILTEMPLATE_EN() {
		return IDMS_USER_ADD_EMAILTEMPLATE_EN;
	}

	public String getIDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN() {
		return IDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN;
	}

	public String getIDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN() {
		return IDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN;
	}

	public String getPRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN() {
		return PRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN;
	}

	public String getPRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN() {
		return PRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN;
	}

	public String getPRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN() {
		return PRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN;
	}

	public String getPRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN() {
		return PRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN;
	}

	public String getPRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN() {
		return PRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN;
	}

	public String getPRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN() {
		return PRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN(String iDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN) {
		IDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN = iDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN(String iDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN) {
		IDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN = iDMS_USER_RESET_PASSWORD_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN(String iDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN) {
		IDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN = iDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN(String iDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN) {
		IDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN = iDMS_USER_RESET_PASSWORD_BLUE_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN(String iDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN) {
		IDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN = iDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN(String iDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN) {
		IDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN = iDMS_USER_REGESTRATION_WITHPWD_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN(
			String iDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN) {
		IDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN = iDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN(
			String iDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN) {
		IDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN = iDMS_USER_REGESTRATION_WITHPWD_BLUE_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_UPDATE_EMAILTEMPLATE_CN(String iDMS_USER_UPDATE_EMAILTEMPLATE_CN) {
		IDMS_USER_UPDATE_EMAILTEMPLATE_CN = iDMS_USER_UPDATE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_UPDATE_EMAILTEMPLATE_EN(String iDMS_USER_UPDATE_EMAILTEMPLATE_EN) {
		IDMS_USER_UPDATE_EMAILTEMPLATE_EN = iDMS_USER_UPDATE_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN(String iDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN) {
		IDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN = iDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN(String iDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN) {
		IDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN = iDMS_USER_UPDATE_BLUE_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_DEFAULT_EMAILTEMPLATE_CN(String iDMS_USER_DEFAULT_EMAILTEMPLATE_CN) {
		IDMS_USER_DEFAULT_EMAILTEMPLATE_CN = iDMS_USER_DEFAULT_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_DEFAULT_EMAILTEMPLATE_EN(String iDMS_USER_DEFAULT_EMAILTEMPLATE_EN) {
		IDMS_USER_DEFAULT_EMAILTEMPLATE_EN = iDMS_USER_DEFAULT_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN(String iDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN) {
		IDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN = iDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN(String iDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN) {
		IDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN = iDMS_USER_DEFAULT_BLUE_EMAILTEMPLATE_EN;
	}

	public void setIDMS_SEND_INVITATION_EMAILTEMPLATE_EN(String iDMS_SEND_INVITATION_EMAILTEMPLATE_EN) {
		IDMS_SEND_INVITATION_EMAILTEMPLATE_EN = iDMS_SEND_INVITATION_EMAILTEMPLATE_EN;
	}

	public void setIDMS_SEND_INVITATION_EMAILTEMPLATE_CN(String iDMS_SEND_INVITATION_EMAILTEMPLATE_CN) {
		IDMS_SEND_INVITATION_EMAILTEMPLATE_CN = iDMS_SEND_INVITATION_EMAILTEMPLATE_CN;
	}

	public void setIDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN(String iDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN) {
		IDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN = iDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_EN;
	}

	public void setIDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN(String iDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN) {
		IDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN = iDMS_SEND_INVITATION_BLUE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_ADD_EMAILTEMPLATE_CN(String iDMS_USER_ADD_EMAILTEMPLATE_CN) {
		IDMS_USER_ADD_EMAILTEMPLATE_CN = iDMS_USER_ADD_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_ADD_EMAILTEMPLATE_EN(String iDMS_USER_ADD_EMAILTEMPLATE_EN) {
		IDMS_USER_ADD_EMAILTEMPLATE_EN = iDMS_USER_ADD_EMAILTEMPLATE_EN;
	}

	public void setIDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN(String iDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN) {
		IDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN = iDMS_USER_ADD_BLUE_EMAILTEMPLATE_CN;
	}

	public void setIDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN(String iDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN) {
		IDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN = iDMS_USER_ADD_BLUE_EMAILTEMPLATE_EN;
	}

	public void setPRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN(String pRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN) {
		PRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN = pRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_CN;
	}

	public void setPRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN(String pRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN) {
		PRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN = pRM_SELF_USER_REGESTRATION_EMAILTEMPLATE_EN;
	}

	public void setPRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN(String pRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN) {
		PRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN = pRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_CN;
	}

	public void setPRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN(String pRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN) {
		PRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN = pRM_INTERNAL_USER_REGESTRATION_EMAILTEMPLATE_EN;
	}

	public void setPRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN(String pRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN) {
		PRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN = pRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_CN;
	}

	public void setPRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN(String pRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN) {
		PRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN = pRM_ECLIPSE_USER_REGESTRATION_EMAILTEMPLATE_EN;
	}
}
