
package com.se.uims.usermanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UIMSV22_UserManagement", targetNamespace = "http://uimsv22.impl.service.ims.schneider.com/", wsdlLocation = "https://ims-int.btsec.dev.schneider-electric.com/IMS-UserManager/UIMSV22/UserManager?wsdl")
public class UIMSV22UserManagement
    extends Service
{

    private final static URL UIMSV22USERMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException UIMSV22USERMANAGEMENT_EXCEPTION;
    private final static QName UIMSV22USERMANAGEMENT_QNAME = new QName("http://uimsv22.impl.service.ims.schneider.com/", "UIMSV22_UserManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ims-int.btsec.dev.schneider-electric.com/IMS-UserManager/UIMSV22/UserManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UIMSV22USERMANAGEMENT_WSDL_LOCATION = url;
        UIMSV22USERMANAGEMENT_EXCEPTION = e;
    }

    public UIMSV22UserManagement() {
        super(__getWsdlLocation(), UIMSV22USERMANAGEMENT_QNAME);
    }

    public UIMSV22UserManagement(WebServiceFeature... features) {
        super(__getWsdlLocation(), UIMSV22USERMANAGEMENT_QNAME, features);
    }

    public UIMSV22UserManagement(URL wsdlLocation) {
        super(wsdlLocation, UIMSV22USERMANAGEMENT_QNAME);
    }

    public UIMSV22UserManagement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UIMSV22USERMANAGEMENT_QNAME, features);
    }

    public UIMSV22UserManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UIMSV22UserManagement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserManagerUIMSV22
     */
    @WebEndpoint(name = "UserManager_UIMSV22_ImplPort")
    public UserManagerUIMSV22 getUserManagerUIMSV22ImplPort() {
        return super.getPort(new QName("http://uimsv22.impl.service.ims.schneider.com/", "UserManager_UIMSV22_ImplPort"), UserManagerUIMSV22.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserManagerUIMSV22
     */
    @WebEndpoint(name = "UserManager_UIMSV22_ImplPort")
    public UserManagerUIMSV22 getUserManagerUIMSV22ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uimsv22.impl.service.ims.schneider.com/", "UserManager_UIMSV22_ImplPort"), UserManagerUIMSV22.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UIMSV22USERMANAGEMENT_EXCEPTION!= null) {
            throw UIMSV22USERMANAGEMENT_EXCEPTION;
        }
        return UIMSV22USERMANAGEMENT_WSDL_LOCATION;
    }

}
