
# This workflow will build a Java project with Maven. Test123
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop/API ]
  pull_request:
    branches: [ develop/API ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn -B package --file idmsc_restapi/schneider-idms/pom.xml
